blank_issues_enabled: false
contact_links:
  - name: "💬 Community Discussions & Questions"
    url: "https://github.com/ajeth23/mene-monitor/discussions"
    about: "Please ask questions, seek help, and share ideas in our GitHub Discussions."
